### ISSUE TITLE
Локализация - api/composition-api-setup.md

### ISSUE THREAD

**Issue by 3lement3** [translation-gang/docs-ru#243]
Добавлю локализацию для страницы API "Composition API: setup()".

REF: https://vuejs.org/api/composition-api-setup.html

**Comment by Leronez** [comment]
@3lement3, приветствую. К сожалению, этот раздел уже взят в перевод и выполнен.  #224 

Чтобы упростить вам поиск раздела для перевода который еще никто не взял в работу, остался только раздел api, ниже подраздела directives.

**Comment by 3lement3** [comment]
Понял
