### ISSUE TITLE
Локализация - guide/essentials/reactivity-fundamentals.md

### ISSUE THREAD

**Issue by Hekikai** [translation-gang/docs-ru#273]
Буду локализовывать вот эту страничку - https://vuejs.org/guide/essentials/reactivity-fundamentals.html

**Comment by Ibochkarev** [comment]
@Hekikai уже сделано https://github.com/translation-gang/docs-ru/pull/274

**Comment by Hekikai** [comment]
@Ibochkarev хорошо, могу тогда прокомментировать некоторые моменты в PR?

**Comment by Ibochkarev** [comment]
> @Ibochkarev хорошо, могу тогда прокомментировать некоторые моменты в PR?

конечно =)
