### ISSUE TITLE
Локализация guide/components/v-mode

### ISSUE THREAD

**Issue by Ibochkarev** [translation-gang/docs-ru#280]
REF: https://vuejs.org/guide/components/v-model.html

**Comment by vladdof** [comment]
![Uploading Снимок экрана 2024-01-23 в 07.57.23.png…]()

**Comment by vladdof** [comment]
![Снимок экрана 2024-01-23 в 07 57 23](https://github.com/translation-gang/docs-ru/assets/38101525/35204a2d-6cb7-437d-a682-0a774e7cd0d8)

пропала страница

**Comment by Ibochkarev** [comment]
@vladdof спс, исправил ссылку

**Comment by srsad** [comment]
Беру на себя
