### ISSUE TITLE
Локализация src/about/community-guide.md

### ISSUE THREAD

**Issue by Ibochkarev** [translation-gang/docs-ru#318]
REF: https://vuejs.org/about/community-guide.html

**Comment by srsad** [comment]
могу взять

**Comment by mnenie** [comment]
если процесс заморожен я могу взять

**Comment by mnenie** [comment]
@Ibochkarev 
готов взять перевод

**Comment by srsad** [comment]
@Ibochkarev прошу прощенья, вынужденно выпадал из сети.
Вернулся, обработал комменты.
Готов и дальше приносить пользу в сообществу)
