### ISSUE TITLE
Закончить перевод api/sfc-script-setup.html

### ISSUE THREAD

**Issue by srsad** [translation-gang/docs-ru#335]
REF: [https://vuejs.org/api/sfc-script-setup.html](https://vuejs.org/api/sfc-script-setup.html)

**Comment by srsad** [comment]
Сам предложил, сам и возьму)

**Comment by Hekikai** [comment]
Я это уже перевел, это залито https://github.com/translation-gang/docs-ru/pull/329

**Comment by Hekikai** [comment]
@srsad тык
