### ISSUE TITLE
Выбор "в Vue" и "во Vue"

### ISSUE THREAD

**Issue by Sdju** [translation-gang/docs-ru#338]
По проекту хаотично разбросаны оба варианта. Решил изучить этот вопрос.
Ознакомился с правилами русского языка. Более корректный вариант: во Vue

Обоснование: 
Предлог `во` выступает перед формами слов, начинающимися сочетаниями "в, ф + согласный". 
Vue - произносим вью - транскрипция `[в'jу]` и именно **в'j** дает "в + согласная"

Нужно сойтись на одном варианте и исправить написанное

**Comment by Hekikai** [comment]
Предлагаю не обращать внимание на транскрипцию, во Vue читается в голове "легче", чем в Vue.  
Две подряд "в" неудобно говорить

**Comment by farid-temuri** [comment]
Я тоже за вариант `во Vue`, так как в самом английском очень много слов, которые даже если пишутся "неудобно", то все-равно произносятся так, чтобы было проще языку. Пример: `module` произносится с доп звуком `а/y` перед `l`, как `маджуал` или `маджуул`, чисто потому, что так языку проще.
