### ISSUE TITLE
/api/composition-api-setup.md

### ISSUE THREAD

**Issue by 3lement3** [translation-gang/docs-ru#8]
Translation [Composition API: setup()](https://vuejs.org/api/composition-api-setup.html)
For local repository this is `src/api/composition-api-setup.md`
Address when the project is launched `api/composition-api-setup.html`

**Comment by Alex-Sokolov** [comment]
@3lement3 такая страница уже была, можно сравнивать и перетаскивать куски готовые https://v3.ru.vuejs.org/ru/api/composition-api.html#setup

**Comment by 3lement3** [comment]
На [русской странице](https://v3.ru.vuejs.org/ru/api/composition-api.html#setup)  текст никак не соответствует [англоязычной версии](https://vuejs.org/api/composition-api-setup.html), если только брать речевые обороты и определения

**Comment by 3lement3** [comment]
+ Эту страницу уже перевели #224
